### ISSUE TITLE
Broken 'Edit on GitHub' link

### ISSUE THREAD

**Issue by suminb** [SongYunSeop/TIL#12]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/136119/177913073-b6c47175-3382-4c3d-b5cb-89c2be71294b.png">

'Edit on GitHub'을 눌렀을 때 [변경 전 GitHub 저장소 주소로 추정되는 주소](https://github.com/songyunseop/%EC%A0%84%EC%A7%80%EC%A0%81%20%EC%86%A1%EC%9C%A4%EC%84%AD%EC%8B%9C%EC%A0%90%20TIL/blob/master/python/flask-server_name.md)로 연결됩니다.

(이슈와는 별개로 TIL 공유 감사드립니다 👍)

**Comment by SongYunSeop** [comment]
@suminb 오모나 선생님 덕분에 수정할 수 있었습니다. 감사합니다!

제가 그동안 관리를 잘 안하고 있었는데, 그로 인해 답변이 느려서 죄송해요 🙏
